<?php

namespace Database\Seeders;

use App\Models\Activity;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class ActivitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        $activities = [
            // --- COOL 1 (Youth & Pro) Activities ---
            [
                'activity_id' => 1,
                'cool_id' => 1,
                'activity_type_id' => 1,
                'name' => 'Ibadah COOL - Kasih yang Mengubahkan',
                'activity_date' => '2026-08-07',
                'start_time' => '19:00:00',
                'end_time' => '21:00:00',
                'location' => 'Rumah Sdr. Andi - Salemba',
                'description' => 'Ibadah mingguan pembukaan bulan Agustus.',
                'status' => 'COMPLETED',
                'is_deleted' => false,
                'created_by' => 2,
                'date_created' => $now,
            ],
            [
                'activity_id' => 2,
                'cool_id' => 1,
                'activity_type_id' => 2,
                'name' => 'Fellowship & Games - Bertumbuh Bersama',
                'activity_date' => '2026-08-14',
                'start_time' => '19:00:00',
                'end_time' => '21:30:00',
                'location' => 'Cafe Salemba Square',
                'description' => 'Makan malam bersama dan games keakraban kelompok.',
                'status' => 'COMPLETED',
                'is_deleted' => false,
                'created_by' => 2,
                'date_created' => $now,
            ],
            [
                'activity_id' => 3,
                'cool_id' => 1,
                'activity_type_id' => 1,
                'name' => 'Ibadah COOL - Hidup dalam Kemenangan',
                'activity_date' => '2026-08-21',
                'start_time' => '19:00:00',
                'end_time' => '21:00:00',
                'location' => 'Rumah Sdr. Daniel',
                'description' => 'Ibadah dan pujian penyembahan.',
                'status' => 'COMPLETED',
                'is_deleted' => false,
                'created_by' => 2,
                'date_created' => $now,
            ],
            [
                'activity_id' => 4,
                'cool_id' => 1,
                'activity_type_id' => 3,
                'name' => 'Doa Bersama & Sharing Firman',
                'activity_date' => '2026-08-28',
                'start_time' => '19:30:00',
                'end_time' => '21:00:00',
                'location' => 'Ruang Doa GBI Salemba Lt. 2',
                'description' => 'Doa syafaat untuk bangsa dan jemaat gereja.',
                'status' => 'COMPLETED',
                'is_deleted' => false,
                'created_by' => 2,
                'date_created' => $now,
            ],
            [
                'activity_id' => 5,
                'cool_id' => 1,
                'activity_type_id' => 1,
                'name' => 'Ibadah COOL - Buah Roh Kudus',
                'activity_date' => '2026-09-04',
                'start_time' => '19:00:00',
                'end_time' => '21:00:00',
                'location' => 'Rumah Sdri. Citra',
                'description' => 'Pendalaman materi buah roh dalam keseharian.',
                'status' => 'COMPLETED',
                'is_deleted' => false,
                'created_by' => 2,
                'date_created' => $now,
            ],
            [
                'activity_id' => 6,
                'cool_id' => 1,
                'activity_type_id' => 1,
                'name' => 'Ibadah COOL - Pengharapan yang Teguh',
                'activity_date' => '2026-09-11',
                'start_time' => '19:00:00',
                'end_time' => '21:00:00',
                'location' => 'Rumah Sdr. Andi',
                'description' => 'Pembahasan iman di tengah tantangan zaman.',
                'status' => 'COMPLETED',
                'is_deleted' => false,
                'created_by' => 2,
                'date_created' => $now,
            ],
            [
                'activity_id' => 7,
                'cool_id' => 1,
                'activity_type_id' => 1,
                'name' => 'Ibadah COOL - Melayani dengan Kasih',
                'activity_date' => '2026-09-18',
                'start_time' => '19:00:00',
                'end_time' => '21:00:00',
                'location' => 'Rumah Sdr. Budi Gunawan',
                'description' => 'Sharing dan persiapan aksi pelayanan jemaat.',
                'status' => 'COMPLETED',
                'is_deleted' => false,
                'created_by' => 2,
                'date_created' => $now,
            ],
            [
                'activity_id' => 8,
                'cool_id' => 1,
                'activity_type_id' => 1,
                'name' => 'Ibadah COOL - Berakar dan Berbuah',
                'activity_date' => '2026-09-25',
                'start_time' => '19:00:00',
                'end_time' => '21:00:00',
                'location' => 'Ruang Serbaguna GBI Salemba',
                'description' => 'Ibadah penutup bulan September.',
                'status' => 'SCHEDULED',
                'is_deleted' => false,
                'created_by' => 2,
                'date_created' => $now,
            ],

            // --- COOL 2 (Family Grace) Activities ---
            [
                'activity_id' => 9,
                'cool_id' => 2,
                'activity_type_id' => 1,
                'name' => 'COOL Family - Mezbah Keluarga',
                'activity_date' => '2026-08-08',
                'start_time' => '18:30:00',
                'end_time' => '20:30:00',
                'location' => 'Kediaman Keluarga Sdr. Handy Kurniawan',
                'description' => 'Membangun mezbah doa dan kasih dalam keluarga.',
                'status' => 'COMPLETED',
                'is_deleted' => false,
                'created_by' => 3,
                'date_created' => $now,
            ],
            [
                'activity_id' => 10,
                'cool_id' => 2,
                'activity_type_id' => 2,
                'name' => 'Potluck & Fellowship Keluarga',
                'activity_date' => '2026-08-22',
                'start_time' => '17:00:00',
                'end_time' => '20:00:00',
                'location' => 'Taman Suropati Menteng',
                'description' => 'Gathering keluarga pasutri dan anak-anak.',
                'status' => 'COMPLETED',
                'is_deleted' => false,
                'created_by' => 3,
                'date_created' => $now,
            ],
            [
                'activity_id' => 11,
                'cool_id' => 2,
                'activity_type_id' => 1,
                'name' => 'COOL Family - Didikan Firman bagi Anak',
                'activity_date' => '2026-09-05',
                'start_time' => '19:00:00',
                'end_time' => '21:00:00',
                'location' => 'Kediaman Keluarga Jonathan Hartono',
                'description' => 'Prinsip alkitabiah dalam mendidik generasi muda.',
                'status' => 'COMPLETED',
                'is_deleted' => false,
                'created_by' => 3,
                'date_created' => $now,
            ],
            [
                'activity_id' => 12,
                'cool_id' => 2,
                'activity_type_id' => 1,
                'name' => 'COOL Family - Komunikasi Suami Istri',
                'activity_date' => '2026-09-19',
                'start_time' => '19:00:00',
                'end_time' => '21:00:00',
                'location' => 'Kediaman Sdri. Ester Natalia',
                'description' => 'Sharing dan konseling pastoral keharmonisan rumah tangga.',
                'status' => 'COMPLETED',
                'is_deleted' => false,
                'created_by' => 3,
                'date_created' => $now,
            ],

            // --- COOL 3 (Joyful Elders) Activities ---
            [
                'activity_id' => 13,
                'cool_id' => 3,
                'activity_type_id' => 1,
                'name' => 'Persekutuan Kaum Senior - Masa Tua Berbuah',
                'activity_date' => '2026-08-12',
                'start_time' => '10:00:00',
                'end_time' => '12:00:00',
                'location' => 'Ruang Kasih GBI Salemba',
                'description' => 'Ibadah pagi dan ramah tamah jemaat lansia.',
                'status' => 'COMPLETED',
                'is_deleted' => false,
                'created_by' => 4,
                'date_created' => $now,
            ],
            [
                'activity_id' => 14,
                'cool_id' => 3,
                'activity_type_id' => 3,
                'name' => 'Doa Pagi Syafaat Senior',
                'activity_date' => '2026-09-09',
                'start_time' => '09:30:00',
                'end_time' => '11:30:00',
                'location' => 'Kediaman Ibu Priscilla Tanujaya',
                'description' => 'Doa bersama untuk cucu, keluarga, dan generasi muda.',
                'status' => 'COMPLETED',
                'is_deleted' => false,
                'created_by' => 4,
                'date_created' => $now,
            ],

            // --- COOL 4 (Campus Fire) Activities ---
            [
                'activity_id' => 15,
                'cool_id' => 4,
                'activity_type_id' => 1,
                'name' => 'Campus Gathering - Api Roh Kudus di Kampus',
                'activity_date' => '2026-08-15',
                'start_time' => '16:00:00',
                'end_time' => '18:00:00',
                'location' => 'Co-Working Space Salemba',
                'description' => 'Pemberdayaan mahasiswa Kristen menjadi terang di kampus.',
                'status' => 'COMPLETED',
                'is_deleted' => false,
                'created_by' => 6,
                'date_created' => $now,
            ],
            [
                'activity_id' => 16,
                'cool_id' => 4,
                'activity_type_id' => 1,
                'name' => 'Campus Gathering - Menghadapi Tekanan Kuliah',
                'activity_date' => '2026-09-12',
                'start_time' => '16:30:00',
                'end_time' => '18:30:00',
                'location' => 'Ruang Pemuda GBI Salemba',
                'description' => 'Sharing integritas akademik dan motivasi belajar dalam Tuhan.',
                'status' => 'COMPLETED',
                'is_deleted' => false,
                'created_by' => 6,
                'date_created' => $now,
            ],

            // --- COOL 5 (Kingdom Builders) Activities ---
            [
                'activity_id' => 17,
                'cool_id' => 5,
                'activity_type_id' => 1,
                'name' => 'Marketplace Apostles - Bisnis Berlandaskan Kerajaan Allah',
                'activity_date' => '2026-08-20',
                'start_time' => '19:30:00',
                'end_time' => '21:30:00',
                'location' => 'Meeting Room Hotel Cikini',
                'description' => 'Sharing etika bisnis Kristen dan kesaksian dunia kerja.',
                'status' => 'COMPLETED',
                'is_deleted' => false,
                'created_by' => 2,
                'date_created' => $now,
            ],
            [
                'activity_id' => 18,
                'cool_id' => 5,
                'activity_type_id' => 1,
                'name' => 'Marketplace Apostles - Finansial yang Alkitabiah',
                'activity_date' => '2026-09-17',
                'start_time' => '19:30:00',
                'end_time' => '21:30:00',
                'location' => 'Kediaman Sdr. Timothy Kusuma',
                'description' => 'Pengelolaan keuangan dan kemurahan hati.',
                'status' => 'COMPLETED',
                'is_deleted' => false,
                'created_by' => 2,
                'date_created' => $now,
            ],

            // --- COOL 6 (Women of Faith) Activities ---
            [
                'activity_id' => 19,
                'cool_id' => 6,
                'activity_type_id' => 1,
                'name' => 'Women of Faith - Wanita Bijaksana & Beriman',
                'activity_date' => '2026-08-19',
                'start_time' => '14:00:00',
                'end_time' => '16:00:00',
                'location' => 'Ruang Ester GBI Salemba',
                'description' => 'Pendalaman firman Amsal 31 bagi wanita Kristen.',
                'status' => 'COMPLETED',
                'is_deleted' => false,
                'created_by' => 5,
                'date_created' => $now,
            ],
            [
                'activity_id' => 20,
                'cool_id' => 6,
                'activity_type_id' => 1,
                'name' => 'Women of Faith - Hati yang Bersyukur',
                'activity_date' => '2026-09-16',
                'start_time' => '14:00:00',
                'end_time' => '16:00:00',
                'location' => 'Kediaman Sdri. Veronika Siregar',
                'description' => 'Pujian penyembahan dan doa saling mendukung sesama wanita.',
                'status' => 'COMPLETED',
                'is_deleted' => false,
                'created_by' => 5,
                'date_created' => $now,
            ],
        ];

        foreach ($activities as $act) {
            Activity::updateOrCreate(['activity_id' => $act['activity_id']], $act);
        }
    }
}
