<?php

namespace Database\Seeders;

use App\Models\Member;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class MemberSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        $members = [
            // --- Jemaat yang sudah tergabung COOL (1 - 24) ---
            [
                'member_id' => 1,
                'member_code' => 'MBR-001',
                'name' => 'Andi Pratama',
                'gender' => 'Laki-laki',
                'birthplace' => 'Jakarta',
                'birthdate' => '1995-04-12',
                'address' => 'Jl. Salemba Raya No. 15, Jakarta Pusat',
                'social_media' => '@andipratama',
                'kom_status' => 'KOM 200',
                'marital_status' => 'Menikah',
                'is_in_cool' => true,
                'phone' => '081211110001',
                'email' => 'andi.pratama@example.com',
                'join_date' => '2025-01-10',
                'status' => 'ACTIVE',
                'is_active' => true,
                'is_deleted' => false,
                'created_by' => 1,
                'date_created' => $now,
            ],
            [
                'member_id' => 2,
                'member_code' => 'MBR-002',
                'name' => 'Budi Gunawan',
                'gender' => 'Laki-laki',
                'birthplace' => 'Bandung',
                'birthdate' => '1992-08-20',
                'address' => 'Jl. Kramat Raya No. 42, Senen, Jakarta Pusat',
                'social_media' => '@budigunawan',
                'kom_status' => 'KOM 400',
                'marital_status' => 'Menikah',
                'is_in_cool' => true,
                'phone' => '081211110002',
                'email' => 'budi.gunawan@example.com',
                'join_date' => '2025-01-15',
                'status' => 'ACTIVE',
                'is_active' => true,
                'is_deleted' => false,
                'created_by' => 1,
                'date_created' => $now,
            ],
            [
                'member_id' => 3,
                'member_code' => 'MBR-003',
                'name' => 'Citra Lestari',
                'gender' => 'Perempuan',
                'birthplace' => 'Surabaya',
                'birthdate' => '1998-11-05',
                'address' => 'Apartemen Menteng Square Tower B, Jakarta Pusat',
                'social_media' => '@citra_lestari',
                'kom_status' => 'KOM 100',
                'marital_status' => 'Belum Menikah',
                'is_in_cool' => true,
                'phone' => '081211110003',
                'email' => 'citra.lestari@example.com',
                'join_date' => '2025-02-01',
                'status' => 'ACTIVE',
                'is_active' => true,
                'is_deleted' => false,
                'created_by' => 1,
                'date_created' => $now,
            ],
            [
                'member_id' => 4,
                'member_code' => 'MBR-004',
                'name' => 'Daniel Christian',
                'gender' => 'Laki-laki',
                'birthplace' => 'Medan',
                'birthdate' => '1990-03-14',
                'address' => 'Jl. Percetakan Negara No. 8, Cempaka Putih, Jakarta Pusat',
                'social_media' => '@danielchristian',
                'kom_status' => 'KOM 300',
                'marital_status' => 'Menikah',
                'is_in_cool' => true,
                'phone' => '081211110004',
                'email' => 'daniel.christian@example.com',
                'join_date' => '2025-02-10',
                'status' => 'ACTIVE',
                'is_active' => true,
                'is_deleted' => false,
                'created_by' => 1,
                'date_created' => $now,
            ],
            [
                'member_id' => 5,
                'member_code' => 'MBR-005',
                'name' => 'Ester Natalia',
                'gender' => 'Perempuan',
                'birthplace' => 'Semarang',
                'birthdate' => '1996-12-25',
                'address' => 'Jl. Cikini Raya No. 18, Jakarta Pusat',
                'social_media' => '@ester.natalia',
                'kom_status' => 'KOM 100',
                'marital_status' => 'Belum Menikah',
                'is_in_cool' => true,
                'phone' => '081211110005',
                'email' => 'ester.natalia@example.com',
                'join_date' => '2025-03-01',
                'status' => 'ACTIVE',
                'is_active' => true,
                'is_deleted' => false,
                'created_by' => 1,
                'date_created' => $now,
            ],
            [
                'member_id' => 6,
                'member_code' => 'MBR-006',
                'name' => 'Fransiscus Kevin',
                'gender' => 'Laki-laki',
                'birthplace' => 'Jakarta',
                'birthdate' => '2000-06-18',
                'address' => 'Jl. Rawasari Barat No. 24, Jakarta Pusat',
                'social_media' => '@frans_kevin',
                'kom_status' => 'Belum KOM',
                'marital_status' => 'Belum Menikah',
                'is_in_cool' => true,
                'phone' => '081211110006',
                'email' => 'fransiscus.kevin@example.com',
                'join_date' => '2025-03-15',
                'status' => 'ACTIVE',
                'is_active' => true,
                'is_deleted' => false,
                'created_by' => 1,
                'date_created' => $now,
            ],
            [
                'member_id' => 7,
                'member_code' => 'MBR-007',
                'name' => 'Grace Angelia',
                'gender' => 'Perempuan',
                'birthplace' => 'Manado',
                'birthdate' => '1997-09-09',
                'address' => 'Jl. Matraman Dalam II No. 7, Jakarta Pusat',
                'social_media' => '@grace_angelia',
                'kom_status' => 'KOM 400',
                'marital_status' => 'Belum Menikah',
                'is_in_cool' => true,
                'phone' => '081211110007',
                'email' => 'grace.angelia@example.com',
                'join_date' => '2025-04-01',
                'status' => 'ACTIVE',
                'is_active' => true,
                'is_deleted' => false,
                'created_by' => 1,
                'date_created' => $now,
            ],
            [
                'member_id' => 8,
                'member_code' => 'MBR-008',
                'name' => 'Handy Kurniawan',
                'gender' => 'Laki-laki',
                'birthplace' => 'Yogyakarta',
                'birthdate' => '1988-02-14',
                'address' => 'Jl. Paseban Timur No. 31, Senen, Jakarta Pusat',
                'social_media' => '@handykurniawan',
                'kom_status' => 'KOM 400',
                'marital_status' => 'Menikah',
                'is_in_cool' => true,
                'phone' => '081211110008',
                'email' => 'handy.kurniawan@example.com',
                'join_date' => '2025-04-10',
                'status' => 'ACTIVE',
                'is_active' => true,
                'is_deleted' => false,
                'created_by' => 1,
                'date_created' => $now,
            ],
            [
                'member_id' => 9,
                'member_code' => 'MBR-009',
                'name' => 'Irene Susanto',
                'gender' => 'Perempuan',
                'birthplace' => 'Jakarta',
                'birthdate' => '1994-07-28',
                'address' => 'Jl. Pegangsaan Timur No. 12, Menteng, Jakarta Pusat',
                'social_media' => '@irenesusanto',
                'kom_status' => 'KOM 200',
                'marital_status' => 'Belum Menikah',
                'is_in_cool' => true,
                'phone' => '081211110009',
                'email' => 'irene.susanto@example.com',
                'join_date' => '2025-05-01',
                'status' => 'ACTIVE',
                'is_active' => true,
                'is_deleted' => false,
                'created_by' => 1,
                'date_created' => $now,
            ],
            [
                'member_id' => 10,
                'member_code' => 'MBR-010',
                'name' => 'Jonathan Hartono',
                'gender' => 'Laki-laki',
                'birthplace' => 'Surabaya',
                'birthdate' => '1991-10-03',
                'address' => 'Jl. Raden Saleh No. 45, Cikini, Jakarta Pusat',
                'social_media' => '@jonathanhartono',
                'kom_status' => 'KOM 300',
                'marital_status' => 'Menikah',
                'is_in_cool' => true,
                'phone' => '081211110010',
                'email' => 'jonathan.hartono@example.com',
                'join_date' => '2025-05-15',
                'status' => 'ACTIVE',
                'is_active' => true,
                'is_deleted' => false,
                'created_by' => 1,
                'date_created' => $now,
            ],
            [
                'member_id' => 11,
                'member_code' => 'MBR-011',
                'name' => 'Kaleb Sitorus',
                'gender' => 'Laki-laki',
                'birthplace' => 'Tarutung',
                'birthdate' => '1999-04-17',
                'address' => 'Jl. Salemba Bluntas No. 14, Paseban, Jakarta Pusat',
                'social_media' => '@kalebsitorus',
                'kom_status' => 'KOM 100',
                'marital_status' => 'Belum Menikah',
                'is_in_cool' => true,
                'phone' => '081211110011',
                'email' => 'kaleb.sitorus@example.com',
                'join_date' => '2025-06-01',
                'status' => 'ACTIVE',
                'is_active' => true,
                'is_deleted' => false,
                'created_by' => 1,
                'date_created' => $now,
            ],
            [
                'member_id' => 12,
                'member_code' => 'MBR-012',
                'name' => 'Lydia Wulandari',
                'gender' => 'Perempuan',
                'birthplace' => 'Solo',
                'birthdate' => '1989-12-01',
                'address' => 'Jl. Kramat Pulo No. 8, Senen, Jakarta Pusat',
                'social_media' => '@lydia_wulan',
                'kom_status' => 'KOM 400',
                'marital_status' => 'Menikah',
                'is_in_cool' => true,
                'phone' => '081211110012',
                'email' => 'lydia.wulandari@example.com',
                'join_date' => '2025-06-15',
                'status' => 'ACTIVE',
                'is_active' => true,
                'is_deleted' => false,
                'created_by' => 1,
                'date_created' => $now,
            ],
            [
                'member_id' => 13,
                'member_code' => 'MBR-013',
                'name' => 'Michael Santoso',
                'gender' => 'Laki-laki',
                'birthplace' => 'Semarang',
                'birthdate' => '1984-05-22',
                'address' => 'Jl. Johar Baru V No. 19, Jakarta Pusat',
                'social_media' => '@michaelsantoso',
                'kom_status' => 'KOM 300',
                'marital_status' => 'Menikah',
                'is_in_cool' => true,
                'phone' => '081211110013',
                'email' => 'michael.santoso@example.com',
                'join_date' => '2025-07-01',
                'status' => 'ACTIVE',
                'is_active' => true,
                'is_deleted' => false,
                'created_by' => 1,
                'date_created' => $now,
            ],
            [
                'member_id' => 14,
                'member_code' => 'MBR-014',
                'name' => 'Novita Sari',
                'gender' => 'Perempuan',
                'birthplace' => 'Bandung',
                'birthdate' => '1993-03-30',
                'address' => 'Jl. Cempaka Putih Tengah No. 11, Jakarta Pusat',
                'social_media' => '@novitasari_id',
                'kom_status' => 'KOM 200',
                'marital_status' => 'Menikah',
                'is_in_cool' => true,
                'phone' => '081211110014',
                'email' => 'novita.sari@example.com',
                'join_date' => '2025-07-15',
                'status' => 'ACTIVE',
                'is_active' => true,
                'is_deleted' => false,
                'created_by' => 1,
                'date_created' => $now,
            ],
            [
                'member_id' => 15,
                'member_code' => 'MBR-015',
                'name' => 'Otniel Ferdinand',
                'gender' => 'Laki-laki',
                'birthplace' => 'Ambon',
                'birthdate' => '1975-08-16',
                'address' => 'Jl. Percetakan Negara IX No. 2, Jakarta Pusat',
                'social_media' => '@otnielferdinand',
                'kom_status' => 'KOM 400',
                'marital_status' => 'Menikah',
                'is_in_cool' => true,
                'phone' => '081211110015',
                'email' => 'otniel.ferdinand@example.com',
                'join_date' => '2025-08-01',
                'status' => 'ACTIVE',
                'is_active' => true,
                'is_deleted' => false,
                'created_by' => 1,
                'date_created' => $now,
            ],
            [
                'member_id' => 16,
                'member_code' => 'MBR-016',
                'name' => 'Priscilla Tanujaya',
                'gender' => 'Perempuan',
                'birthplace' => 'Jakarta',
                'birthdate' => '1978-01-24',
                'address' => 'Jl. Diponegoro No. 34, Menteng, Jakarta Pusat',
                'social_media' => '@priscillatanujaya',
                'kom_status' => 'KOM 400',
                'marital_status' => 'Menikah',
                'is_in_cool' => true,
                'phone' => '081211110016',
                'email' => 'priscilla.tan@example.com',
                'join_date' => '2025-08-10',
                'status' => 'ACTIVE',
                'is_active' => true,
                'is_deleted' => false,
                'created_by' => 1,
                'date_created' => $now,
            ],
            [
                'member_id' => 17,
                'member_code' => 'MBR-017',
                'name' => 'Rendy Pangestu',
                'gender' => 'Laki-laki',
                'birthplace' => 'Bogor',
                'birthdate' => '2002-10-11',
                'address' => 'Jl. Salemba Tengah Gg. IV No. 5, Jakarta Pusat',
                'social_media' => '@rendy_pangestu',
                'kom_status' => 'KOM 100',
                'marital_status' => 'Belum Menikah',
                'is_in_cool' => true,
                'phone' => '081211110017',
                'email' => 'rendy.pangestu@example.com',
                'join_date' => '2025-09-01',
                'status' => 'ACTIVE',
                'is_active' => true,
                'is_deleted' => false,
                'created_by' => 1,
                'date_created' => $now,
            ],
            [
                'member_id' => 18,
                'member_code' => 'MBR-018',
                'name' => 'Stefani Anggraeni',
                'gender' => 'Perempuan',
                'birthplace' => 'Malang',
                'birthdate' => '2001-07-19',
                'address' => 'Kost Salemba UI, Jl. Salemba Raya, Jakarta Pusat',
                'social_media' => '@stefanianggraeni',
                'kom_status' => 'KOM 100',
                'marital_status' => 'Belum Menikah',
                'is_in_cool' => true,
                'phone' => '081211110018',
                'email' => 'stefani.ang@example.com',
                'join_date' => '2025-09-10',
                'status' => 'ACTIVE',
                'is_active' => true,
                'is_deleted' => false,
                'created_by' => 1,
                'date_created' => $now,
            ],
            [
                'member_id' => 19,
                'member_code' => 'MBR-019',
                'name' => 'Timothy Kusuma',
                'gender' => 'Laki-laki',
                'birthplace' => 'Jakarta',
                'birthdate' => '1987-09-04',
                'address' => 'Jl. Cempaka Putih Barat No. 33, Jakarta Pusat',
                'social_media' => '@timothykusuma',
                'kom_status' => 'KOM 300',
                'marital_status' => 'Menikah',
                'is_in_cool' => true,
                'phone' => '081211110019',
                'email' => 'timothy.kusuma@example.com',
                'join_date' => '2025-10-01',
                'status' => 'ACTIVE',
                'is_active' => true,
                'is_deleted' => false,
                'created_by' => 1,
                'date_created' => $now,
            ],
            [
                'member_id' => 20,
                'member_code' => 'MBR-020',
                'name' => 'Veronika Siregar',
                'gender' => 'Perempuan',
                'birthplace' => 'Medan',
                'birthdate' => '1991-02-14',
                'address' => 'Jl. Kenari Raya No. 40, Senen, Jakarta Pusat',
                'social_media' => '@veronikasiregar',
                'kom_status' => 'KOM 200',
                'marital_status' => 'Belum Menikah',
                'is_in_cool' => true,
                'phone' => '081211110020',
                'email' => 'veronika.siregar@example.com',
                'join_date' => '2025-10-15',
                'status' => 'ACTIVE',
                'is_active' => true,
                'is_deleted' => false,
                'created_by' => 1,
                'date_created' => $now,
            ],
            [
                'member_id' => 21,
                'member_code' => 'MBR-021',
                'name' => 'Widodo Hendarto',
                'gender' => 'Laki-laki',
                'birthplace' => 'Yogyakarta',
                'birthdate' => '1968-11-28',
                'address' => 'Jl. Kramat VI No. 12, Senen, Jakarta Pusat',
                'social_media' => '@widodohendarto',
                'kom_status' => 'KOM 400',
                'marital_status' => 'Menikah',
                'is_in_cool' => true,
                'phone' => '081211110021',
                'email' => 'widodo.hendarto@example.com',
                'join_date' => '2025-11-01',
                'status' => 'ACTIVE',
                'is_active' => true,
                'is_deleted' => false,
                'created_by' => 1,
                'date_created' => $now,
            ],
            [
                'member_id' => 22,
                'member_code' => 'MBR-022',
                'name' => 'Yuliana Megawati',
                'gender' => 'Perempuan',
                'birthplace' => 'Semarang',
                'birthdate' => '1970-04-18',
                'address' => 'Jl. Paseban Raya No. 6, Senen, Jakarta Pusat',
                'social_media' => '@yulianamegawati',
                'kom_status' => 'KOM 400',
                'marital_status' => 'Janda / Duda',
                'is_in_cool' => true,
                'phone' => '081211110022',
                'email' => 'yuliana.megawati@example.com',
                'join_date' => '2025-11-15',
                'status' => 'ACTIVE',
                'is_active' => true,
                'is_deleted' => false,
                'created_by' => 1,
                'date_created' => $now,
            ],
            [
                'member_id' => 23,
                'member_code' => 'MBR-023',
                'name' => 'Zefanya Natanael',
                'gender' => 'Laki-laki',
                'birthplace' => 'Bandung',
                'birthdate' => '2003-05-30',
                'address' => 'Jl. Salemba Tengah No. 42, Jakarta Pusat',
                'social_media' => '@zefanyanatanael',
                'kom_status' => 'KOM 100',
                'marital_status' => 'Belum Menikah',
                'is_in_cool' => true,
                'phone' => '081211110023',
                'email' => 'zefanya.natanael@example.com',
                'join_date' => '2025-12-01',
                'status' => 'ACTIVE',
                'is_active' => true,
                'is_deleted' => false,
                'created_by' => 1,
                'date_created' => $now,
            ],
            [
                'member_id' => 24,
                'member_code' => 'MBR-024',
                'name' => 'Debora Elisabeth',
                'gender' => 'Perempuan',
                'birthplace' => 'Surabaya',
                'birthdate' => '1986-06-14',
                'address' => 'Jl. Cikini Kramat No. 7, Jakarta Pusat',
                'social_media' => '@deboraelisabeth',
                'kom_status' => 'KOM 300',
                'marital_status' => 'Menikah',
                'is_in_cool' => true,
                'phone' => '081211110024',
                'email' => 'debora.elisabeth@example.com',
                'join_date' => '2025-12-10',
                'status' => 'ACTIVE',
                'is_active' => true,
                'is_deleted' => false,
                'created_by' => 1,
                'date_created' => $now,
            ],

            // --- Jemaat yang Belum Bergabung COOL (25 - 36) ---
            [
                'member_id' => 25,
                'member_code' => 'MBR-025',
                'name' => 'Kezia Priscilla',
                'gender' => 'Perempuan',
                'birthplace' => 'Jakarta',
                'birthdate' => '2001-01-19',
                'address' => 'Jl. Kenari II No. 10, Senen, Jakarta Pusat',
                'social_media' => '@keziapriscilla',
                'kom_status' => 'Belum KOM',
                'marital_status' => 'Belum Menikah',
                'is_in_cool' => false,
                'phone' => '081211110025',
                'email' => 'kezia.priscilla@example.com',
                'join_date' => '2026-01-05',
                'status' => 'ACTIVE',
                'is_active' => true,
                'is_deleted' => false,
                'created_by' => 1,
                'date_created' => $now,
            ],
            [
                'member_id' => 26,
                'member_code' => 'MBR-026',
                'name' => 'Lucas Wibowo',
                'gender' => 'Laki-laki',
                'birthplace' => 'Semarang',
                'birthdate' => '1985-05-17',
                'address' => 'Jl. Kramat Lontar No. 27, Jakarta Pusat',
                'social_media' => '@lucaswibowo',
                'kom_status' => 'KOM 100',
                'marital_status' => 'Menikah',
                'is_in_cool' => false,
                'phone' => '081211110026',
                'email' => 'lucas.wibowo@example.com',
                'join_date' => '2026-01-12',
                'status' => 'ACTIVE',
                'is_active' => true,
                'is_deleted' => false,
                'created_by' => 1,
                'date_created' => $now,
            ],
            [
                'member_id' => 27,
                'member_code' => 'MBR-027',
                'name' => 'Meilani Simanjuntak',
                'gender' => 'Perempuan',
                'birthplace' => 'Pematang Siantar',
                'birthdate' => '1995-05-02',
                'address' => 'Jl. Percetakan Negara IV No. 15, Jakarta Pusat',
                'social_media' => '@meilanisimanjuntak',
                'kom_status' => 'Belum KOM',
                'marital_status' => 'Belum Menikah',
                'is_in_cool' => false,
                'phone' => '081211110027',
                'email' => 'meilani.s@example.com',
                'join_date' => '2026-01-20',
                'status' => 'NEW',
                'is_active' => true,
                'is_deleted' => false,
                'created_by' => 1,
                'date_created' => $now,
            ],
            [
                'member_id' => 28,
                'member_code' => 'MBR-028',
                'name' => 'Nathaniel Chandra',
                'gender' => 'Laki-laki',
                'birthplace' => 'Jakarta',
                'birthdate' => '1992-12-12',
                'address' => 'Apartemen Salemba Residence Lantai 8, Jakarta Pusat',
                'social_media' => '@nathanielchandra',
                'kom_status' => 'KOM 200',
                'marital_status' => 'Menikah',
                'is_in_cool' => false,
                'phone' => '081211110028',
                'email' => 'nathaniel.c@example.com',
                'join_date' => '2026-02-01',
                'status' => 'ACTIVE',
                'is_active' => true,
                'is_deleted' => false,
                'created_by' => 1,
                'date_created' => $now,
            ],
            [
                'member_id' => 29,
                'member_code' => 'MBR-029',
                'name' => 'Olivia Patricia',
                'gender' => 'Perempuan',
                'birthplace' => 'Surabaya',
                'birthdate' => '1999-03-08',
                'address' => 'Jl. Raden Saleh I No. 4, Cikini, Jakarta Pusat',
                'social_media' => '@oliviapatricia',
                'kom_status' => 'KOM 100',
                'marital_status' => 'Belum Menikah',
                'is_in_cool' => false,
                'phone' => '081211110029',
                'email' => 'olivia.p@example.com',
                'join_date' => '2026-02-15',
                'status' => 'ACTIVE',
                'is_active' => true,
                'is_deleted' => false,
                'created_by' => 1,
                'date_created' => $now,
            ],
            [
                'member_id' => 30,
                'member_code' => 'MBR-030',
                'name' => 'Paulus Wijanarko',
                'gender' => 'Laki-laki',
                'birthplace' => 'Solo',
                'birthdate' => '1972-07-21',
                'address' => 'Jl. Kramat Sentiong No. 35, Senen, Jakarta Pusat',
                'social_media' => '@pauluswijanarko',
                'kom_status' => 'KOM 300',
                'marital_status' => 'Menikah',
                'is_in_cool' => false,
                'phone' => '081211110030',
                'email' => 'paulus.w@example.com',
                'join_date' => '2026-03-01',
                'status' => 'ACTIVE',
                'is_active' => true,
                'is_deleted' => false,
                'created_by' => 1,
                'date_created' => $now,
            ],
            [
                'member_id' => 31,
                'member_code' => 'MBR-031',
                'name' => 'Queen Stephanie',
                'gender' => 'Perempuan',
                'birthplace' => 'Manado',
                'birthdate' => '2004-09-15',
                'address' => 'Jl. Rawasari Timur No. 18, Jakarta Pusat',
                'social_media' => '@queenstephanie',
                'kom_status' => 'Belum KOM',
                'marital_status' => 'Belum Menikah',
                'is_in_cool' => false,
                'phone' => '081211110031',
                'email' => 'queen.s@example.com',
                'join_date' => '2026-03-10',
                'status' => 'NEW',
                'is_active' => true,
                'is_deleted' => false,
                'created_by' => 1,
                'date_created' => $now,
            ],
            [
                'member_id' => 32,
                'member_code' => 'MBR-032',
                'name' => 'Reinhard Siregar',
                'gender' => 'Laki-laki',
                'birthplace' => 'Medan',
                'birthdate' => '1981-06-25',
                'address' => 'Jl. Paseban Barat No. 22, Senen, Jakarta Pusat',
                'social_media' => '@reinhardsiregar',
                'kom_status' => 'KOM 200',
                'marital_status' => 'Menikah',
                'is_in_cool' => false,
                'phone' => '081211110032',
                'email' => 'reinhard.s@example.com',
                'join_date' => '2026-04-01',
                'status' => 'ACTIVE',
                'is_active' => true,
                'is_deleted' => false,
                'created_by' => 1,
                'date_created' => $now,
            ],
            [
                'member_id' => 33,
                'member_code' => 'MBR-033',
                'name' => 'Sherly Noviana',
                'gender' => 'Perempuan',
                'birthplace' => 'Palembang',
                'birthdate' => '1997-11-14',
                'address' => 'Jl. Cempaka Putih Timur No. 9, Jakarta Pusat',
                'social_media' => '@sherlynoviana',
                'kom_status' => 'KOM 100',
                'marital_status' => 'Belum Menikah',
                'is_in_cool' => false,
                'phone' => '081211110033',
                'email' => 'sherly.n@example.com',
                'join_date' => '2026-04-15',
                'status' => 'ACTIVE',
                'is_active' => true,
                'is_deleted' => false,
                'created_by' => 1,
                'date_created' => $now,
            ],
            [
                'member_id' => 34,
                'member_code' => 'MBR-034',
                'name' => 'Titus Pangaribuan',
                'gender' => 'Laki-laki',
                'birthplace' => 'Balige',
                'birthdate' => '1990-08-30',
                'address' => 'Jl. Percetakan Negara II No. 17, Jakarta Pusat',
                'social_media' => '@tituspangaribuan',
                'kom_status' => 'Belum KOM',
                'marital_status' => 'Menikah',
                'is_in_cool' => false,
                'phone' => '081211110034',
                'email' => 'titus.p@example.com',
                'join_date' => '2026-05-01',
                'status' => 'ACTIVE',
                'is_active' => true,
                'is_deleted' => false,
                'created_by' => 1,
                'date_created' => $now,
            ],
            [
                'member_id' => 35,
                'member_code' => 'MBR-035',
                'name' => 'Ursula Permata',
                'gender' => 'Perempuan',
                'birthplace' => 'Yogyakarta',
                'birthdate' => '1965-02-10',
                'address' => 'Jl. Salemba Tengah Gg. VIII No. 3, Jakarta Pusat',
                'social_media' => '@ursulapermata',
                'kom_status' => 'KOM 400',
                'marital_status' => 'Janda / Duda',
                'is_in_cool' => false,
                'phone' => '081211110035',
                'email' => 'ursula.p@example.com',
                'join_date' => '2026-05-20',
                'status' => 'ACTIVE',
                'is_active' => true,
                'is_deleted' => false,
                'created_by' => 1,
                'date_created' => $now,
            ],
            [
                'member_id' => 36,
                'member_code' => 'MBR-036',
                'name' => 'Victor Jonathan',
                'gender' => 'Laki-laki',
                'birthplace' => 'Jakarta',
                'birthdate' => '2005-08-17',
                'address' => 'Jl. Kramat Raya No. 90, Jakarta Pusat',
                'social_media' => '@victorjonathan',
                'kom_status' => 'Belum KOM',
                'marital_status' => 'Belum Menikah',
                'is_in_cool' => false,
                'phone' => '081211110036',
                'email' => 'victor.j@example.com',
                'join_date' => '2026-06-01',
                'status' => 'NEW',
                'is_active' => true,
                'is_deleted' => false,
                'created_by' => 1,
                'date_created' => $now,
            ],
        ];

        foreach ($members as $member) {
            Member::updateOrCreate(['member_id' => $member['member_id']], $member);
        }
    }
}
